// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real_Mission8_group2_7.Models;

#nullable disable

namespace RealMission8_group2_7.Migrations
{
    [DbContext(typeof(Mission8ApplicationContext))]
    [Migration("20240228200310_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Real_Mission8_group2_7.Models.TaskModel", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("category")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("duedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("quadrant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
